[theme]
primaryColor = "#1f77b4"         # A deep Seaborn-style blue
backgroundColor = "#f0f2f6"      # Light gray/blue
secondaryBackgroundColor = "#e6eff7"  # Slightly deeper blue-gray
textColor = "#262730"
font = "sans serif"
